quarkiverse/quarkus-logging-splunk

deployment/pom.xml, deployment/src/test/java/io/quarkiverse/logging/splunk/AbstractMockServerTest.java, deployment/src/test/java/io/quarkiverse/logging/splunk/LoggingSplunkMinimalConfigTest.java, deployment/src/test/java/io/quarkiverse/logging/splunk/LoggingSplunkSendErrorTest.java, deployment/src/test/java/io/quarkiverse/logging/splunk/LoggingSplunkTest.java, deployment/src/test/java/io/quarkiverse/logging/splunk/LoggingSplunkWithMetadataTest.java
Splunk client uses an asynchronous HTTP queue, so we need to wait for mockserver to receive the call before trying to assert (was pretty rare in local, but happens more frequently in Github CI)
Create an abstract class for the mock-server lifecycle.
=> Avoid race conditions in tests

deployment/pom.xml, deployment/src/test/java/io/quarkiverse/logging/splunk/LoggingSplunkDisabledTest.java, deployment/src/test/java/io/quarkiverse/logging/splunk/LoggingSplunkTest.java, docs/pom.xml, integration-test/pom.xml, pom.xml, runtime/pom.xml, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkErrorCallback.java
There's a new minor version of Quarkus in town.
This version has broken the extension build because of a minor issue, however we need to bump the extension to 2.x in order to support our RedHat Build or Quarkus branch (rhbq/1.11).
- Switch quarkus-logging-splunk to 2.0
- Fix DelayedHandler class cast issue
=> Bump quarkus minor version to 1.13.2.Final

docs/modules/ROOT/pages/index.adoc
It was OK in repo README, but not in userguide.
=> Fix groupId in userguide

pom.xml
We have an issue in the quarkus-bom right now (in the `main` branch only) and this breaks Ecosystem CI. I'm
not entirely sure how much time it will take us to fix it given it's a
complex multi-projects one and, given the workaround is simple, I
thought it would be a good idea to apply it and get CI green.
=> Work around an issue in the quarkus-bom to get CI green

.github/project.yml
Something went wrong during https://github.com/quarkiverse/quarkus-logging-splunk/pull/17/, let's re-try.
I didn't see any "re-run" from Github actions UI, probably because it triggers on a PR closure.
=> Re-try release 2.0

.github/project.yml
There was no breaking changes on Quarkus side, so can be considered a minor.
Can be used as basis for the RHBQ 2.2 branch of the extension
=> Release 2.1

README.md, pom.xml
The Quarkiverse extensions are now listed on code.quarkus.io (https://code.quarkus.io/?e=io.quarkiverse.logging.splunk%3Aquarkus-logging-splunk&extension-search=origin:other%20splunk ), but the current description is inherited from parent pom.
=> Add Maven description, as used by code.quarkus.io

docs/pom.xml, pom.xml
Replaces #68 
- Compile to Java 11 bytecode (Quarkus 2+)
- Let quarkiverse-parent manage asciidoctor versions
=> Align with quarkiverse-parent 9

runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkErrorCallback.java
Users who wish to customize their Splunk HEC error behavior (such as
incrementing a Micrometer Counter) might still find it desirable to
delegate to SplunkErrorCallback for its useful core functionality.
Making the class public will allow for this use-case.
---
Here's an example of my situation:
```java
/**
* A custom Quarkus-ified Splunk HEC error handler so that we can track failures in a Prometheus
* metric and then alert if that metric exceeds acceptable parameters.
*/
@Slf4j
@ApplicationScoped
public class CountingSplunkErrorCallback implements ErrorCallback {
private final ErrorCallback delegatedCallback;
private final Counter failureCounter;
public CountingSplunkErrorCallback(MeterRegistry meterRegistry) {
// Only one ErrorCallback can be registered. The standard callback is useful …
```
=> Make SplunkErrorCallback public

deployment/src/test/java/io/quarkiverse/logging/splunk/LoggingSplunkAsyncTest.java, deployment/src/test/resources/application-splunk-logging-async.properties, runtime/src/main/java/io/quarkiverse/logging/splunk/AsyncConfig.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkConfig.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkLogHandlerRecorder.java
Resolves  #114
This is based on what Quarkus is doing internally: https://github.com/quarkusio/quarkus/blob/f2508a9d89d5fa258e742c14aee7eeaf0bbc2a72/core/runtime/src/main/java/io/quarkus/runtime/logging/LoggingSetupRecorder.java#L577
Would be nice to add a section about async in the doc.
=> Support async log handler

.github/project.yml, docs/modules/ROOT/pages/includes/quarkus-log-handler-splunk.adoc, docs/pom.xml
Failing the regular build if the doc in not synched might be risky if Quarkus changes the doc output due to upstream nightly builds
=> Resync the doc and retry release 2.4

deployment/src/test/java/io/quarkiverse/logging/splunk/LoggingSplunkSendErrorTest.java, runtime/pom.xml
This should hopefully fix the random failure in https://github.com/quarkiverse/quarkiverse/issues/37 and other PR builds.
Also replace mockito-core by mockito-inline, so that spies work on JDK17 classes in SplunkErrorCallbackTest.
=> Fix flaky LoggingSplunkSendErrorTest

deployment/src/test/java/io/quarkiverse/logging/splunk/LoggingSplunkFlatSerializationTest.java, deployment/src/test/resources/application-splunk-logging-flat.properties, docs/modules/ROOT/pages/includes/quarkus-log-handler-splunk.adoc, docs/modules/ROOT/pages/index.adoc, integration-test/src/main/resources/application.properties, integration-test/src/test/java/io/quarkiverse/logging/splunk/SplunkLoggingTest.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkConfig.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkLogHandlerRecorder.java
In flat serialization setting metadata-source-type to _json prevent the indexing on splunk side. In flat and raw mode, metadata-source-type is no longer sent unless explicitly configured.
Also fix a typo in the documented structured endpoint path.
Note: we can't easily test both modes in the same integration test without https://github.com/quarkiverse/quarkus-logging-splunk/issues/156
=> Make metadata-source-type optional

runtime/pom.xml
As of Mockito 5.3, mockito-inline is no longer published, it has become the default since mockito 5.0
Relates to https://github.com/quarkusio/quarkus/pull/33037
This should fix the nightly https://github.com/quarkiverse/quarkiverse/issues/37#issuecomment-1534191862
=> Replace mockito-inline by mockito-core

runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkErrorCallback.java
This is a follow-up pull request after https://github.com/quarkiverse/quarkus-logging-splunk/pull/111. 
Having the constructors protected makes the class SplunkErrorCallback still unusable for the same use-case.
=> Make SplunkErrorCallback's contructors public

deployment/src/main/java/io/quarkiverse/logging/splunk/LoggingSplunkProcessor.java, deployment/src/test/java/io/quarkiverse/logging/splunk/LoggingSplunkNamedHandlerConfigTest.java, deployment/src/test/resources/application-splunk-logging-named-handler.properties, docs/modules/ROOT/pages/includes/quarkus-log-handler-splunk.adoc, docs/modules/ROOT/pages/index.adoc, integration-test/src/main/resources/application.properties, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkConfig.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkHandlerConfig.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkLogHandlerRecorder.java
I guess named handlers are managed as expected with a defaulting for any config property to the root splunk configuration.
I was a bit sad about having had to duplicate the properties from the root level and the named handler ones, but I did not find how to customize the default value to detect in the recorder when to fetch the root value or the handler value when a default value is defined upfront. Any idea? 
Fixes #156
=> Support named handlers #156

.github/project.yml
Forgot that we need to open a PR for workflow to be triggered to release, so switching to 3.1.2 directly
=> chore: Release 3.1.2

docs/modules/ROOT/pages/includes/quarkus-log-handler-splunk.adoc, pom.xml, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkConfig.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkLogHandlerRecorder.java
Backporting bugfixes to the Quarkus 2.x branch:
* #228
* CVE fix for https://github.com/splunk/splunk-library-javalogging/releases/tag/1.11.8
=> 2.5.x backports

runtime/src/main/resources/META-INF/quarkus-extension.yaml
This will fix some data that is otherwise deducted from Maven (name, RedHat as sponsor) and adding missing data (no categories, no status, and no link to guide). These metadata are used on https://quarkus.io/extensions/io.quarkiverse.logging.splunk/quarkus-logging-splunk/
=> Add extension metadata, incl. sponsor

integration-test/src/test/java/io/quarkiverse/logging/splunk/SplunkResource.java
Attempt to fix https://github.com/quarkiverse/quarkiverse/issues/37 
Nightly builds started failing ~2 weeks ago, so using a tag that is older than that: https://hub.docker.com/layers/splunk/splunk/9.2.0.1/images/sha256-0b1c082353c4da2b6a2e01c8c8159b010a84f430d34fe3d4ea7e6039be90e525?context=explore
=> fix(ci): use a fixed tag for splunk/splunk image

deployment/src/main/java/io/quarkiverse/logging/splunk/LoggingSplunkProcessor.java, deployment/src/test/java/io/quarkiverse/logging/splunk/LoggingSplunkFilteringTest.java, deployment/src/test/resources/application-splunk-logging-filtering.properties, docs/modules/ROOT/pages/includes/quarkus-log-handler-splunk.adoc, integration-test/src/main/java/io/quarkiverse/logging/splunk/SensitiveLogFilter.java, integration-test/src/main/java/io/quarkiverse/logging/splunk/SplunkHandlerResource.java, integration-test/src/main/resources/application.properties, integration-test/src/test/java/io/quarkiverse/logging/splunk/SplunkLoggingTest.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkHandlerConfig.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkLogHandler.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkLogHandlerRecorder.java
Closes #244 
Some logic has to be duplicated from LoggingResourceProcessor/LoggingSetupRecorder due to lack of build items.
Also Quarkus core registers a global LogCleanupFilter after named handlers initialization, so we need to implement #setFilter rather as an #addFilter.
=> feat: support named log filter

deployment/src/main/java/io/quarkiverse/logging/splunk/DevServicesLoggingSplunkProcessor.java, deployment/src/test/java/io/quarkiverse/logging/splunk/AbstractMockServerTest.java, deployment/src/test/java/io/quarkiverse/logging/splunk/LoggingSplunkMandatoryConfigTest.java, docs/modules/ROOT/pages/includes/quarkus-log-handler-splunk.adoc, pom.xml, runtime/src/main/java/io/quarkiverse/logging/splunk/AsyncConfig.java, runtime/src/main/java/io/quarkiverse/logging/splunk/DevServicesLoggingSplunkRuntimeConfig.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkConfig.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkHandlerConfig.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkLogHandlerRecorder.java, runtime/src/main/java/io/quarkiverse/logging/splunk/config/build/DevServicesLoggingSplunkBuildTimeConfig.java, runtime/src/main/java/io/quarkiverse/logging/splunk/config/build/SplunkBuildConfig.java, runtime/src/test/java/io/quarkiverse/logging/splunk/SplunkLogHandlerRecorderTest.java, test-utils/src/test/java/io/quarkiverse/logging/splunk/test/LoggingSplunkInjectingTestResourceTest.java
Also update quarkiverse-parent to version 18.
Consequences:
* ConfigRoot needed to be migrated to ConfigMapping with transformation in interfaces. Update everywhere the configuration mapping is used with method calls.
Biggest impact was on named handlers, the devservices entry where considered as a key of the named handlers map. A filtering had to be added in SplunkLogHandlerRecorder.
There are no breaking changes.
=> feat(quarkus): Migrate to Quarkus 3.15.1

pom.xml
When adding a custom repository, central repo inherited from Maven parent is tried last, instead of first. This causes builds to be slower, as most dependencies are resolved via central.
cf https://github.com/quarkiverse/quarkus-logging-splunk/issues/293#issuecomment-2437537429
=> ci: add back central repo for efficiency

.github/workflows/build.yml, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkLogHandler.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkLogHandlerRecorder.java, runtime/src/test/java/io/quarkiverse/logging/splunk/SplunkLogHandlerRecorderTest.java
This commit solves a discrepancy between blocking and async handlers, where the async handler would ignore any specified batchInterval due to the activation of autoflush by default.
=> Disable AsyncHandler autoflush with batch delay

.github/workflows/build.yml, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkLogHandler.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkLogHandlerRecorder.java, runtime/src/test/java/io/quarkiverse/logging/splunk/SplunkLogHandlerRecorderTest.java
This commit solves a discrepancy between blocking and async handlers, where the async handler would ignore any specified batchInterval due to the activation of autoflush by default.
=> Disable AsyncHandler autoflush

deployment/src/main/java/io/quarkiverse/logging/splunk/SplunkContainer.java
Splunk added a launch option to acknolwedge https://www.splunk.com/en_us/legal/splunk-general-terms.html
That's the problem of depending on :latest when there's a breaking change.
However the Splunk images also have an "expiration", so if we hardcode the tag, it will refuse to start after 6 months...
The fix impacts:
* The CI builds of this repo (seen via https://github.com/quarkiverse/quarkiverse/issues/37)
* The DevService => we'll need to release a patch.
=> fix: add new mandatory arg of splunk latest image

docs/modules/ROOT/pages/includes/quarkus-logging-splunk.adoc, docs/modules/ROOT/pages/includes/quarkus-logging-splunk_quarkus.log.adoc, docs/modules/ROOT/pages/index.adoc, docs/pom.xml, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkErrorCallback.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkHandlerConfig.java, runtime/src/main/java/io/quarkiverse/logging/splunk/SplunkLogHandlerRecorder.java, runtime/src/test/java/io/quarkiverse/logging/splunk/SplunkErrorCallbackTest.java
Introduces a new configuration option to disable the printing of log events to stdout when a communication error with splunk occurs. 
This is useful in scenarios where applications manages sensitive data such as PCI, PII or security token.
Also fix issue build by adding a asciidoctorj-diagram-plantuml dependency due to asciidoctorj-diagram to 3.0.1
=> fix: add option to disable printing log events to stdout
